### ISSUE TITLE
Self-hosted Influxdb

### ISSUE THREAD

**Issue by elzik** [jonfairbanks/emeter#12]
I am using the Docker image via Docker Hub. With the `INFLUX_HOST` environment variable, is the expectation that I can point this tool to my own [self-hosted instance if InfluxDb](https://github.com/influxdata/influxdb) (v2.4.0)? I have tried but I get the following error. Am I simply trying to do something that isn't possible?

```
Traceback (most recent call last):
  File "/home/python/app/main.py", line 62, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/python/app/main.py", line 20, in main
    client = InfluxDBClient(url=HOST, token=TOKEN, org=ORG)
  File "/home/python/.local/lib/python3.9/site-packages/influxdb_client/client/influxdb_client.py", line 55, in __init__
    super().__init__(url=url, token=token, debug=debug, timeout=timeout, enable_gzip=enable_gzip, org=org,
  File "/home/python/.local/lib/python3.9/site-packages/influxdb_client/client/_base.py", line 59, in __init__
    self.auth_header_value = "Token " + auth_token
TypeError: can only concatenate str (not "NoneType") to str
Exception ignored in: <function InfluxDBClient.__del__ at 0x1497a69101f0>
Traceback (most recent call last):
  File "/home/python/.local/lib/python3.9/site-packages/influxdb_client/client/influxdb_client.py", line 262, in __del__
AttributeError: 'InfluxDBClient' object has no attribute 'api_client'
EMeter is running...
```

**Comment by jonfairbanks** [comment]
Let me try to test this locally but this should be possible. Will make changes if necessary.

**Comment by jonfairbanks** [comment]
Hey @elzik, I was able to get this to run locally like so:

First, initiate an InfluxDB instance and init the required values:
```
docker run -d -p 8086:8086 \
    -e DOCKER_INFLUXDB_INIT_MODE=setup \
    -e DOCKER_INFLUXDB_INIT_ORG=my-org \
    -e DOCKER_INFLUXDB_INIT_BUCKET=power-usage \
    -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=bXkgY29vbCB2YWx1ZQo= \
    influxdb
```

Then update the included docker-compose.yml to use these new values:
```
services:
  emeter:
    image: jonfairbanks/emeter
    restart: always
    environment:
      - DEVICE=TestDevice1
      - INFLUX_HOST=http://1.2.3.4:8086
      - INFLUX_TOKEN=bXkgY29vbCB2YWx1ZQo=
      - INFLUX_ORG=my-org
      - INFLUX_BUCKET=power-usage
      - PLUG=1.2.3.4
```
Hopefully this helps... let me know!

**Comment by elzik** [comment]
> Hey @elzik, I was able to get this to run locally like so:
> <snip>
> Hopefully this helps... let me know!

Yes, this worked and after comparing it with my `docker run` command I realised that I had copied the trailing colon after the `INFLUX_TOKEN` token from your readme. Mystery solved, thanks!
